reports:
  - group_id
  - [ INT ]
  - status_id
  - [ INT ]
  - { start_date: [ start_date_year, start_date_month, start_date_day ] }
  - [ DATE ]
  - { end_date: [ end_date_year, end_date_month, end_date_day ] }
  - [ DATE ]
add_document:
  - document
  - [ NOT_BLANK ]
  - replaced_document_id
  - [ INT ]
update_status:
  - status_id
  - [ NOT_BLANK, INT ]
  - group_id
  - [ INT ]
  - comment
  - [ [ LENGTH, 0, 8192 ] ]
