add:
  - title
  - [ NOT_BLANK, [ LENGTH, 0, 64 ] ]
  - description
  - [ NOT_BLANK, [ LENGTH, 0, 1024 ] ]
add_document:
  - document
  - [ NOT_BLANK ]
  - replaced_document_id
  - [ INT ]
add_action:
  - action_id
  - [ NOT_BLANK, INT ]
  - status_id
  - [ NOT_BLANK, INT ]
  - group_id
  - [ INT ]
  - comment
  - [ [ LENGTH, 0, 1024 ] ]
