reports:
  - group_id
  - [ INT ]
  - status_id
  - []
  - start_time_month
  - [ INT ]
  - start_time_day
  - [ INT ]
  - start_time_year
  - [ INT ]
  - end_time_month
  - [ INT ]
  - end_time_day
  - [ INT ]
  - end_time_year
  - [ INT ]
add_document:
  - document
  - [ NOT_BLANK ]
  - replaced_document_id
  - [ INT ]
update_status:
  - status_id
  - [ NOT_BLANK, INT ]
  - group_id
  - [ INT ]
  - comment
  - [ [ LENGTH, 0, 8192 ] ]
