reports:
  - query
  - []
  - query_field
  - [ INT ]
  # These should be INT, but FormValidator::Simple barfs on multivalues currently
  - process_id
  - []
  - inactive_processes
  - [ INT ]
  - group_id
  - []
  - status_id
  - []
  - { start_date: [ start_date_year, start_date_month, start_date_day ] }
  - [ DATE_ALLOWING_BLANK ]
  - { end_date: [ end_date_year, end_date_month, end_date_day ] }
  - [ DATE_ALLOWING_BLANK ]
  - page
  - [ INT ]
edit:
  - title
  - [ NOT_BLANK, [ LENGTH, 0, 64 ] ]
  - description
  - [ NOT_BLANK, [ LENGTH, 0, 8192 ] ]
add_document:
  - document
  - [ NOT_BLANK ]
  - replaced_document_id
  - [ INT ]
include_document:
  - document_id
  - [ INT ]
remove_document:
  - document_id
  - [ INT ]
update_status:
  - status_id
  - [ NOT_BLANK, INT ]
  - group_id
  - [ INT ]
  - comment
  - [ [ LENGTH, 0, 8192 ] ]
