reports:
  - group_id
  - [ INT ]
  - status_id
  - []
  - { start_time: [start_time_year, start_time_month, start_time_day] }
  - [ DATE ]
  - { end_time: [end_time_year, end_time_month, end_time_day] }
  - [ DATE ]
add_document:
  - document
  - [ NOT_BLANK ]
  - replaced_document_id
  - [ INT ]
update_status:
  - status_id
  - [ NOT_BLANK, INT ]
  - group_id
  - [ INT ]
  - comment
  - [ [ LENGTH, 0, 8192 ] ]
