add: &process
  - name
  - [ NOT_BLANK ]
edit: *process
add_step:
  - name
  - [ NOT_BLANK ]
  - role_id
  - [ NOT_BLANK, INT ]
delete_step:
  - step_id
  - [ NOT_BLANK, INT ]
move_step_up: &move
  - step_id
  - [ NOT_BLANK, INT ]
move_step_down: *move
