add: &process
  - name
  - [ NOT_BLANK, [ LENGTH, 0, 32 ] ]
  - description
  - [ [ LENGTH, 0, 8192 ] ]
edit: *process
add_step:
  - name
  - [ NOT_BLANK, [ LENGTH, 0, 32 ] ]
  - role_id
  - [ NOT_BLANK, INT ]
delete_step:
  - step_id
  - [ NOT_BLANK, INT ]
move_step_up: &move
  - step_id
  - [ NOT_BLANK, INT ]
move_step_down: *move
