add: &process
  - name
  - [ NOT_BLANK, [ LENGTH, 0, 64 ] ]
  - description
  - [ [ LENGTH, 0, 8192 ] ]
  - enabled 
  - [ INT ]
edit: *process
add_step:
  - name
  - [ NOT_BLANK, [ LENGTH, 0, 64 ] ]
  - role_id
  - [ NOT_BLANK, INT ]
delete_step:
  - step_id
  - [ NOT_BLANK, INT ]
move_step_up: &move
  - step_id
  - [ NOT_BLANK, INT ]
move_step_down: *move
add_request:
  - title
  - [ NOT_BLANK, [ LENGTH, 0, 64 ] ]
  - description
  - [ NOT_BLANK, [ LENGTH, 0, 8192 ] ]
  - group_id
  - [ NOT_BLANK, INT ]
