edit:
  - name
  - [ NOT_BLANK, [ LENGTH, 0, 64 ] ]
  - description
  - [ [ LENGTH, 0, 8192 ] ]
  - type
  - [ NOT_BLANK, INT ]
  - min_length
  - [ INT ]
  - max_length
  - [ INT ]
  - optional
  - [ INT ]
