add:
  - title
  - [ NOT_BLANK ]
  - description
  - [ NOT_BLANK ]
add_document:
  - document_id
  - [ INT ]
add_action:
  - action_id
  - [ NOT_BLANK, INT ]
  - status_id
  - [ NOT_BLANK, INT ]
  - comment
  - []
