index:
  - query
  - [ NOT_BLANK, ASCII ]
add:
  - users 
  - [ NOT_BLANK ]
edit:
  - username
  - [ NOT_BLANK ]
  - display_name
  - [ NOT_BLANK ]
  - email
  - [ NOT_BLANK ]
  - wants_email
  - [ INT ]
  - active
  - [ INT ]
toggle_email:
  - wants_email
  - [ INT ]
add_group_role: &role
  - group_id
  - [ NOT_BLANK, INT ]
  - role_id
  - [ NOT_BLANK, INT ]
delete_group_role: *role
